### ISSUE TITLE
Validictory will no longer be maintained as of January 1st 2018

### ISSUE THREAD

**Issue by jamesturk** [jpmckinney/validictory#114]
Update: I've decided that I intend to cease support / maintenance on Jan 1 2018.  The existing library will continue to work & I'll roll one final release around the end of the year, but that'll be the end. 

I think that https://github.com/Julian/jsonschema would be a better choice going forward as it has a lot more usage and supports different versions of the JSON schema spec (w/ a plan to support the latest draft as well)

I'm also curious to hear if there are people using validictory that strongly prefer it for any reason.

If someone wants to maintain the project I'm definitely open to that as well, I'd gladly push the library to a new org.

**Comment by SankarBalaji** [comment]
Hi jamesturk , 
              We are using validictory for our product which uses json. I find the module which is easy to use and understand(I haven't explored the other module you have mentioned though). but I feel you need not make validictory as deprecated instead wait for people to move to newer products. 
              We might not need active support , but still i believe this module has the potential to do its job.

**Comment by jamesturk** [comment]
Deprecation would of course allow people to continue using the project but would signify that it is no longer going to be actively maintained.  I've decided that deprecation will most likely occur officially as of Jan 1st 2018.  I'm still open to hearing arguments but for my main use of the library (github.com/openstates) I was able to swap the library usage out in <1 hour.

**Comment by mmariani** [comment]
I personally think the sematic of "required" in jsonschema, with a list of names, is much more prone to errors than a boolean near each property name. I'm switching now and it bothers me.

**Comment by jamesturk** [comment]
I 100% agree w/ that, but it doesn't seem like supporting a slightly divergent version from the spec is going to be worthwhile since the spec has already moved on

**Comment by dmr** [comment]
I'm a bit sad to see validictory go away but I understand the reasons.
In general jsonschema implementations in python are mostly outdated IMO and I feel it's better to say "Validictory will no longer be maintained" than to not actively work on it.

Thank you for your work, I guess we'll be switching to jsonschema then.

**Comment by jpmckinney** [comment]
FYI, I have taken on maintenance, mainly because an old project has heavy monkeypatching of validictory, and it is much easier to change one line (`from collections ...` to `from collections.abc ...`) than to switch to jsonschema.

Maintenance will be for Python upgrades only. No new features. Undecided on bugfixes.
