### ISSUE TITLE
Configure pypi.yml workflow once PyPI access granted

### ISSUE THREAD

**Issue by jpmckinney** [jpmckinney/validictory#117]
https://docs.pypi.org/trusted-publishers/adding-a-publisher/

**Comment by bennettgoble** [comment]
Hey, @jpmckinney. Firstly: thanks for volunteering to patch up this library and get a new version published!

I'm in a similar sounding bind: it would be a lot easier for me to swap in a version of validictory with the `from collections.abc import Container, Mapping` fix in than replace its use with jsonschema.

Do you know when a new version might be published? No pressure, I just want to understand whether I should fork and patch this library up in an internal pip repo or wait a bit. Thx!

**Comment by jpmckinney** [comment]
Good reminder - I’ve pinged the author a reminder to share PyPI access.

**Comment by jpmckinney** [comment]
1.1.3 is released :)
